"""
postprocessor.py - Merge audio tracks and combine with the edited video.

Responsibilities
----------------
1. Mix generated audio (from MMAudio etc.) with the original audio track.
2. Mux the final audio onto the edited video-only track.

The original audio was separated in the preprocessor and kept untouched.
If an audio generation tool produced new audio (e.g. rain sounds),
it is mixed with the original before muxing.
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def _run(cmd: list[str], description: str = "") -> subprocess.CompletedProcess:
    logger.debug("Running: %s", " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"[{description}] failed (rc={result.returncode}):\n{result.stderr}"
        )
    return result


# ── Audio mixing ──────────────────────────────────────────────────────────

def _mean_volume_db(audio_path: Path) -> Optional[float]:
    """Return the mean volume (dBFS) of *audio_path* via ffmpeg
    volumedetect, or None on failure."""
    try:
        r = subprocess.run(
            [
                "ffmpeg", "-hide_banner", "-nostats", "-i", str(audio_path),
                "-af", "volumedetect", "-f", "null", "-",
            ],
            capture_output=True, text=True, timeout=60,
        )
    except Exception:
        return None
    for line in r.stderr.splitlines():
        if "mean_volume:" in line:
            try:
                return float(line.split("mean_volume:")[-1].split("dB")[0].strip())
            except ValueError:
                return None
    return None


def _balanced_original_volume(
    preserved_audio: Path,
    generated_audio: Path,
    base_original_volume: float,
    *,
    preserve_gap_db: float = 14.0,
    max_boost_db: float = 18.0,
    silence_floor_db: float = -50.0,
) -> float:
    """Compute an original-track volume that keeps the preserved bed
    (BGM/ambience in *preserved_audio*) audible under a much louder
    *generated_audio* layer.

    Mechanism: a quiet preserved bed (e.g. -39 dB) summed with a loud
    generated SFX (e.g. -9 dB) is masked ~30 dB down and becomes
    inaudible. We BOOST the bed (never attenuate the requested SFX) so
    it sits at most `preserve_gap_db` below the generated track.

    Returns `base_original_volume` unchanged when measurement fails, the
    bed is essentially silent (nothing to preserve), or the bed is
    already loud enough. The boost is clamped to `max_boost_db`.
    """
    p = _mean_volume_db(preserved_audio)
    g = _mean_volume_db(generated_audio)
    if p is None or g is None:
        return base_original_volume
    # Essentially-silent bed → nothing meaningful to rescue; don't
    # amplify noise/hiss up into audibility.
    if p < silence_floor_db:
        return base_original_volume
    # dB the bed must rise to sit `preserve_gap_db` below the generated.
    boost_db = (g - preserve_gap_db) - p
    if boost_db <= 0:
        return base_original_volume   # bed already audible enough
    boost_db = min(boost_db, max_boost_db)
    factor = 10.0 ** (boost_db / 20.0)
    logger.info(
        "[Postprocess] loudness-balance: preserved=%.1f dB generated=%.1f dB "
        "→ boost bed +%.1f dB (x%.2f) so it stays within %.0f dB of the SFX",
        p, g, boost_db, factor, preserve_gap_db,
    )
    return base_original_volume * factor


def mix_audio_tracks(
    original_audio: Path,
    generated_audio: Path,
    output_path: Path,
    original_volume: float = 1.0,
    generated_volume: float = 0.7,
    auto_balance_preserved: bool = False,
) -> Path:
    """
    Mix original and generated audio using ffmpeg's amix filter.

    Parameters
    ----------
    original_audio     : Path to the original audio extracted by preprocessor.
    generated_audio    : Path to the audio generated by MMAudio / other tool.
    output_path        : Where to write the mixed audio file.
    original_volume    : Volume multiplier for the original track (0.0 – 2.0).
    generated_volume   : Volume multiplier for the generated track (0.0 – 2.0).
    auto_balance_preserved : When True, measure both tracks and boost the
                       original/preserved track so a quiet bed (BGM,
                       ambience) is not masked by a much louder generated
                       SFX. Only boosts; never attenuates the SFX.

    Returns
    -------
    Path to the mixed audio file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if auto_balance_preserved:
        original_volume = _balanced_original_volume(
            original_audio, generated_audio, original_volume,
        )

    cmd = [
        "ffmpeg", "-y",
        "-i", str(original_audio),
        "-i", str(generated_audio),
        "-filter_complex",
        (
            f"[0:a]volume={original_volume}[a0];"
            f"[1:a]volume={generated_volume}[a1];"
            f"[a0][a1]amix=inputs=2:duration=first:dropout_transition=2:normalize=0[a]"
        ),
        "-map", "[a]",
        "-c:a", "aac",
        "-b:a", "192k",
        str(output_path),
    ]
    _run(cmd, "mix_audio_tracks")
    logger.info("[Postprocess] mixed audio → %s", output_path)
    return output_path


def splice_replacement_audio(
    original_audio: Path,
    replacement_bed_audio: Path,
    replacement_voice_audio: Path,
    output_path: Path,
    start: float,
    end: float,
    original_volume: float = 1.0,
    bed_volume: float = 1.0,
    voice_volume: float = 1.0,
    duration: float | None = None,
) -> Path:
    """Replace one local audio window while preserving the rest.

    The output layout is:
      original_audio[0:start] +
      mix(replacement_bed_audio[start:end], replacement_voice_audio[0:window]) +
      original_audio[end:]

    This is for speech rewrites where SAM may remove a speaker from
    the whole track, but only one transcript window should change.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    start = max(0.0, float(start))
    end = max(start + 0.05, float(end))
    window = max(0.05, end - start)

    parts: list[str] = []
    concat_labels: list[str] = []

    if start > 0.01:
        parts.append(
            f"[0:a]atrim=0:{start:.3f},asetpts=PTS-STARTPTS,"
            f"volume={original_volume}[pre]"
        )
        concat_labels.append("[pre]")

    parts.extend([
        (
            f"[1:a]atrim={start:.3f}:{end:.3f},asetpts=PTS-STARTPTS,"
            f"volume={bed_volume}[bed]"
        ),
        (
            f"[2:a]atrim=0:{window:.3f},asetpts=PTS-STARTPTS,"
            f"apad=pad_dur={window:.3f},atrim=0:{window:.3f},"
            f"volume={voice_volume}[voice]"
        ),
        (
            "[bed][voice]amix=inputs=2:duration=first:"
            "dropout_transition=0:normalize=0[mid]"
        ),
    ])
    concat_labels.append("[mid]")

    if duration is None or end < float(duration) - 0.01:
        post_end = "" if duration is None else f":{float(duration):.3f}"
        parts.append(
            f"[0:a]atrim={end:.3f}{post_end},asetpts=PTS-STARTPTS,"
            f"volume={original_volume}[post]"
        )
        concat_labels.append("[post]")

    filter_complex = ";".join(parts) + ";" + "".join(concat_labels) + (
        f"concat=n={len(concat_labels)}:v=0:a=1[a]"
    )

    cmd = [
        "ffmpeg", "-y",
        "-i", str(original_audio),
        "-i", str(replacement_bed_audio),
        "-i", str(replacement_voice_audio),
        "-filter_complex", filter_complex,
        "-map", "[a]",
        "-c:a", "aac",
        "-b:a", "192k",
        str(output_path),
    ]
    _run(cmd, "splice_replacement_audio")
    logger.info(
        "[Postprocess] spliced local replacement %.3f→%.3fs → %s",
        start, end, output_path,
    )
    return output_path


# ── Video + Audio merge ───────────────────────────────────────────────────

def merge_audio_video(
    video_path: Path,
    audio_path: Optional[Path],
    output_path: Path,
) -> Path:
    """
    Merge an audio track with the edited video.

    - If audio_path is None (original video was silent), just copy the video.
    - Uses ``-c copy`` for both streams → lossless, near-instant.
    - ``-shortest`` ensures the output duration matches the shorter track.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if audio_path is None or not audio_path.exists():
        logger.info("[Postprocess] no audio to merge — copying video as-is")
        cmd = ["ffmpeg", "-y", "-i", str(video_path), "-c", "copy", str(output_path)]
        _run(cmd, "copy_video")
    else:
        logger.info("[Postprocess] merging audio (%s) + video (%s)",
                     audio_path.name, video_path.name)
        # Pad audio with silence up to video length (apad + aresample)
        # and cut at video end. This guarantees we NEVER truncate visual
        # content when the audio track is slightly shorter than the
        # edited video. Audio must be re-encoded (apad requires a filter),
        # so we bounce to AAC here instead of -c:a copy.
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_path),
            "-i", str(audio_path),
            "-filter_complex",
            "[1:a]aresample=async=1:first_pts=0,apad[aout]",
            "-map", "0:v:0",
            "-map", "[aout]",
            "-c:v", "copy",
            "-c:a", "aac",
            "-b:a", "192k",
            "-shortest",           # now bounded by the (padded) audio which
                                   # is ≥ video length → video is preserved
            str(output_path),
        ]
        _run(cmd, "merge_audio_video")

    logger.info("[Postprocess] final output → %s", output_path)
    return output_path


# ── High-level postprocess entry point ────────────────────────────────────

def postprocess(
    video_path: Path,
    original_audio: Optional[Path],
    generated_audio: Optional[Path],
    output_path: Path,
    original_audio_volume: float = 1.0,
    generated_audio_volume: float = 0.7,
) -> Path:
    """
    Full postprocessing pipeline.

    Cases:
      1. original + generated audio → mix both, then mux onto video
      2. original audio only        → mux original audio onto video
      3. generated audio only       → mux generated audio onto video
      4. no audio at all            → copy video as-is

    Parameters
    ----------
    video_path              : Edited video (no audio track).
    original_audio          : Audio extracted from the original input video.
    generated_audio         : Audio produced by MMAudio or similar tool.
    output_path             : Final output video file path.
    original_audio_volume   : Volume of original audio when mixing (0.0–2.0).
    generated_audio_volume  : Volume of generated audio when mixing (0.0–2.0).
    """
    # Determine which audio to use
    has_original = original_audio is not None and original_audio.exists()
    has_generated = generated_audio is not None and generated_audio.exists()

    if has_original and has_generated:
        # Case 1: mix both audio tracks
        logger.info("[Postprocess] mixing original audio + generated audio")
        mixed_audio = output_path.parent / "mixed_audio.aac"
        mix_audio_tracks(
            original_audio=original_audio,          # type: ignore[arg-type]
            generated_audio=generated_audio,        # type: ignore[arg-type]
            output_path=mixed_audio,
            original_volume=original_audio_volume,
            generated_volume=generated_audio_volume,
        )
        final_audio: Optional[Path] = mixed_audio

    elif has_original:
        # Case 2: original audio only
        logger.info("[Postprocess] using original audio only (no generated audio)")
        final_audio = original_audio

    elif has_generated:
        # Case 3: generated audio only (original video was silent)
        logger.info("[Postprocess] using generated audio only (no original audio)")
        final_audio = generated_audio

    else:
        # Case 4: no audio
        logger.info("[Postprocess] no audio tracks available")
        final_audio = None

    return merge_audio_video(video_path, final_audio, output_path)
